services:
  product-service:
    build: ./product-service
    ports:
      - "${PRODUCT_PORT}:${PRODUCT_PORT}"
    environment:
      - PORT=${PRODUCT_PORT}
      - OTLP_URL=${OTLP_URL}
    labels:
      service: ${PRODUCT_SERVICE}
      application: ${APPLICATION}
      environment: ${ENVIRONMENT}
    logging:
      driver: loki
      options:
        loki-url: http://${OBSERVABILITY_HOST}:${LOKI_PORT}/loki/api/v1/push
        labels: service,application,environment
  user-service:
    build: ./user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    environment:
      - PORT=${USER_PORT}
      - OTLP_URL=${OTLP_URL}
    labels:
      service: ${USER_SERVICE}
      application: ${APPLICATION}
      environment: ${ENVIRONMENT}
    logging:
      driver: loki
      options:
        loki-url: http://${OBSERVABILITY_HOST}:${LOKI_PORT}/loki/api/v1/push
        labels: service,application,environment
  frontend-service:
    build: ./frontend-service
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    environment:
      - PORT=${FRONTEND_PORT}
      - OTLP_URL=${OTLP_URL}
      - PRODUCT_SERVICE_URL=http://product-service:${PRODUCT_PORT}
      - USER_SERVICE_URL=http://user-service:${USER_PORT}
    labels:
      service: ${FRONTEND_SERVICE}
      application: ${APPLICATION}
      environment: ${ENVIRONMENT}
    depends_on:
      - product-service
      - user-service
    logging:
      driver: loki
      options:
        loki-url: http://${OBSERVABILITY_HOST}:${LOKI_PORT}/loki/api/v1/push
        labels: service,application,environment
